{{ if not (has "docker-service-kill" .Values.experiments.disabled) }}
---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Kills the docker service on the application node to check the resiliency.
kind: ChaosExperiment
metadata:
  name: docker-service-kill
  labels:
<<<<<<< HEAD
    instance: {{ .Release.Name }}
    chart: {{ include "kubernetes-chaos.chart" . }}
    litmuschaos.io/version: {{ .Chart.AppVersion }}
=======
    {{- include "kubernetes-chaos.labels" . | indent 4 }}
>>>>>>> eb0e859e20aee51bc690b747b1b6dbfd380f19e3
spec:
  definition:
    scope: Cluster
    permissions:
      - apiGroups:
          - ""
          - "batch"
          - "apps"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "pods/log"
          - "events"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
      - apiGroups:
          - ""
        resources:
          - "nodes"
        verbs:
          - "get"
          - "list"
<<<<<<< HEAD
    image: "{{ .Values.image.litmus.repository }}:{{ .Values.image.litmus.tag }}"
    imagePullPolicy: {{ .Values.image.litmus.pullPolicy }}
    args:
    - -c
    - ansible-playbook ./experiments/generic/docker_service_kill/docker_service_kill_ansible_logic.yml -i /etc/ansible/hosts -vv; exit 0
    command:
    - /bin/bash
    env:
    - name: ANSIBLE_STDOUT_CALLBACK
      value: 'default'

=======
    image: "{{ .Values.image.litmusGO.repository }}:{{ .Values.image.litmusGO.tag }}"
    imagePullPolicy: {{ .Values.image.litmusGO.pullPolicy }}
    args:
    - -c
    - ./experiments -name docker-service-kill
    command:
    - /bin/bash
    env:
>>>>>>> eb0e859e20aee51bc690b747b1b6dbfd380f19e3
    - name: TOTAL_CHAOS_DURATION
      value: '90' # in seconds

    # Period to wait before injection of chaos in sec
    - name: RAMP_TIME
      value: ''

    - name: LIB
      value: 'litmus'
<<<<<<< HEAD
    labels:
      name: docker-service-kill
      app.kubernetes.io/part-of: litmus
=======

    - name: NODE_LABEL
      value: ''

    # provide lib image
    - name: LIB_IMAGE
      value: 'ubuntu:16.04' 
            
    # provide the target node name
    - name: TARGET_NODE
      value: ''

    labels:
      name: docker-service-kill
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/host-path-usage: "true"
>>>>>>> eb0e859e20aee51bc690b747b1b6dbfd380f19e3
{{ end }}
