{{ if not (has "pod-memory-hog" .Values.experiments.disabled) }}
---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Injects memory consumption on pods belonging to an app deployment
kind: ChaosExperiment
metadata:
  name: pod-memory-hog
  labels:
<<<<<<< HEAD
    instance: {{ .Release.Name }}
    chart: {{ include "kubernetes-chaos.chart" . }}
    litmuschaos.io/version: {{ .Chart.AppVersion }}
=======
    {{- include "kubernetes-chaos.labels" . | indent 4 }}
>>>>>>> eb0e859e20aee51bc690b747b1b6dbfd380f19e3
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - "batch"
          - "apps"
          - "apps.openshift.io"
          - "argoproj.io"
          - "litmuschaos.io"
        resources:
          - "jobs"
          - "pods"
          - "pods/log"
          - "replicationcontrollers"
          - "deployments"
          - "statefulsets"
          - "daemonsets"
          - "replicasets"
          - "deploymentconfigs"
          - "rollouts"
          - "pods/exec"
          - "events"
          - "chaosengines"
          - "chaosexperiments"
          - "chaosresults"
        verbs:
          - "create"
          - "list"
          - "get"
          - "patch"
          - "update"
          - "delete"
          - "deletecollection"
    image: "{{ .Values.image.litmusGO.repository }}:{{ .Values.image.litmusGO.tag }}"
    imagePullPolicy: {{ .Values.image.litmusGO.pullPolicy }}
    args:
    - -c
    - ./experiments -name pod-memory-hog
    command:
    - /bin/bash
    env:

    - name: TOTAL_CHAOS_DURATION
      value: '60'

    # Enter the amount of memory in megabytes to be consumed by the application pod
    # default: 500 (Megabytes)
    - name: MEMORY_CONSUMPTION
      value: '500'

    # Percentage of total pods to target
    - name: PODS_AFFECTED_PERC
      value: ''

    # Period to wait before injection of chaos in sec
    - name: RAMP_TIME
      value: ''

    # Env var that describes the library used to execute the chaos
    # Default: litmus. Supported values: litmus, pumba
    - name: LIB
      value: 'litmus'

    # It is used in pumba lib only   
    - name: LIB_IMAGE
      value: "{{ .Values.image.litmusLIBImage.repository }}:{{ .Values.image.litmusLIBImage.tag }}"

     ## It is used in pumba lib only    
    - name: STRESS_IMAGE
      value: "{{ .Values.image.resourceChaos.repository }}:{{ .Values.image.resourceChaos.tag }}"

    - name: TARGET_PODS
      value: ''

    ## it defines the sequence of chaos execution for multiple target pods
    ## supported values: serial, parallel
    - name: SEQUENCE
      value: 'parallel'     

<<<<<<< HEAD
    - name: SOCKET_PATH
      value: "{{ .Values.environment.socketPath }}" 
=======
    # provide the name of container runtime
    # for litmus LIB, it supports docker, containerd, crio
    # for pumba LIB, it supports docker only
    - name: CONTAINER_RUNTIME
      value: "{{ .Values.environment.runtime }}"
    
    # provide the container runtime socket path
    # default set to std docker sock file path
    - name: SOCKET_PATH
      value: "{{ .Values.environment.socketPath }}"
>>>>>>> eb0e859e20aee51bc690b747b1b6dbfd380f19e3

    labels:
      name: pod-memory-hog
      app.kubernetes.io/part-of: litmus
<<<<<<< HEAD
=======
      app.kubernetes.io/runtime-api-usage: "true"
>>>>>>> eb0e859e20aee51bc690b747b1b6dbfd380f19e3
{{ end }}
