---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-chaos.name" . }}-chaos-admin
  labels:
<<<<<<< HEAD
    instance: {{ .Release.Name }}
    chart: {{ include "kubernetes-chaos.chart" . }} 
    litmuschaos.io/version: {{ .Chart.AppVersion }} 
=======
    {{- include "kubernetes-chaos.labels" . | indent 4 }}
>>>>>>> eb0e859e20aee51bc690b747b1b6dbfd380f19e3
