apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litmus-portal.fullname" . }}-admin-config
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "litmus-portal.labels" . | nindent 4 }}
data:
  AgentScope: "{{ .Values.portalScope }}"
  AgentNamespace: "{{ .Release.Namespace }}"
  DataBaseServer: "{{ .Values.adminConfig.DataBaseServer }}"
  JWTSecret: "{{ .Values.adminConfig.JWTSecret }}"
  DB_USER: "{{ .Values.adminConfig.DBUSER }}"
  DB_PASSWORD: "{{ .Values.adminConfig.DBPASSWORD }}"
