apiVersion: v1
<<<<<<< HEAD
appVersion: "1.13.3"
description: A Helm chart to install litmus chaos experiments for kubernetes category (chaos-chart)
name: kubernetes-chaos
version: 2.9.0
=======
appVersion: "2.14.0"
description: A Helm chart to install litmus chaos experiments for kubernetes category (chaos-chart)
name: kubernetes-chaos
version: 2.28.0
>>>>>>> eb0e859e20aee51bc690b747b1b6dbfd380f19e3
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - kubernetes
maintainers:
  - name: ksatchit
    email: karthik.s@mayadata.io
  - name: chandankumar4
    email: chandan.kumar@zopsmart.com
  - name: jasstkn
    email: jasssstkn@yahoo.com
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png
