{{- $persistence := .Values.mongo.persistence -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "litmus-portal.fullname" . }}-mongo-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litmus-portal.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ include "litmus-portal.fullname" . }}-mongo
spec:
  accessModes:
    - {{ $persistence.accessMode }}
  resources:
    requests:
      storage: {{ $persistence.size }}
  {{- if $persistence.storageClass }}
  storageClassName: {{ $persistence.storageClass }}
  {{- end }}
