apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "litmus-portal.fullname" . }}-upgrade-agent-cp
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: upgrade-agent
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.upgrade-agent.control-plane.image.repository }}:{{ .Values.upgrade-agent.control-plane.image.tag }}
          imagePullPolicy: {{ .Values.upgrade-agent.control-plane.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "litmus-portal.fullname" . }}-admin-config